version: '3.7'

services:
  db:
    container_name: "tesst_db"
    platform: linux/x86_64
    build:
      context: .
      dockerfile: db.Dockerfile
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "tesst"
      MYSQL_USER: "tester"
      MYSQL_PASSWORD: "secret"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  app:
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
networks:
  default:
volumes:
  mysql_data:
